### ISSUE TITLE
스팟 등록 수정

### ISSUE THREAD

**Issue by soprue** [eodya/eodya-frontend#20]
### Todo

- [x] 이미지 업로드 시 리사이징 하여 용량 최적화
- [ ] 스팟 등록 페이지에서 검색 시 이미 등록되어 있는 스팟들은 후기 남기기 버튼 뜨게 하기
- [ ] 스팟 등록 완료하면 redux에 해당 값 추가하기…?

### 작업 기간

2024.04.08 ~ 2024.04.15
