### ISSUE TITLE
메인 기능 추가 및 수정

### ISSUE THREAD

**Issue by Banal972** [eodya/eodya-frontend#23]
### Todo

- [x] 근처 명소 스크롤 수정 ( 더보기 클릭시 페이지 이동 )
- [x] 스팟 상세 후기 스크롤 수정 ( 더보기 클릭시 페이지 이동 )
- [x] 등록된 스팟 지도에 스팟 띄우기
- [x] 스팟 클릭시 마커 변경
- [x] 스팟 검색 기능 추가

### 작업 기간

2024.04.08 ~ 2024.04.15

<br />

## 참고 자료 (optional)
https://velog.io/@msdio/%EC%84%A0%ED%83%9D%EB%90%9C-%EC%A7%80%EB%8F%84-%EB%A7%88%EC%BB%A4%EC%9D%98-%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%A5%BC-%EB%B3%80%EA%B2%BD%ED%95%98%EB%8A%94-%EC%9E%91%EC%9D%80-%EB%A1%9C%EC%A7%81

**Comment by Banal972** [comment]
API가 아직 수정중이라 검색기능은 따로 더미데이터를 생성해서 작업했습니다.
