### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by Banal972** [eodya/eodya-frontend#3]
### Todo

- [x] 메인페이지 레이아웃 설계
- [x] 좌표에 따라 스팟(마커) 설계
- [x] 스팟 클릭시 뷰페이지 레이아웃 설계
- [x] 스팟 클릭시 뷰페이지 기능

### 작업 기간
2024.03.25 ~ 2024.03.00

## 참고 자료 (optional)

카카오맵
https://apis.map.kakao.com/
날씨
https://openweathermap.org/
공공데이터 관광
https://www.data.go.kr/data/15101578/openapi.do#/
