### ISSUE TITLE
공통 컴포넌트

### ISSUE THREAD

**Issue by Banal972** [eodya/eodya-frontend#4]
### Todo

- [x] 하단 메뉴 레이아웃 설계
- [x] 검색 버튼 레이아웃 설계
- [x] 공통 버튼 레이아웃 설계 (북마크 , 상태 같은것) 

### 작업 기간
2024.03.25 ~ 2024.03.00
